---
abstract: 'Data::Faker plugin for metasyntactic data'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Faker-MetaSyntactic
recommends:
  Task::MetaSyntactic: '0'
requires:
  Acme::MetaSyntactic: '1.000'
  Data::Faker: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Data-Faker-MetaSyntactic
  repository: http://github.com/book/Data-Faker-MetaSyntactic.git
version: '1.000'
